//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertasSistema
    {
        public int AlertaID { get; set; }
        public string TipoAlerta { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaAlerta { get; set; }
        public string Usuario { get; set; }
    }
}
