//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaMovimientosCaja
    {
        public int AuditoriaID { get; set; }
        public Nullable<int> MovimientoID { get; set; }
        public Nullable<int> SubMayorID { get; set; }
        public string TipoOperacion { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Concepto { get; set; }
        public string ReferenciaExterna { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public string UsuarioOperacion { get; set; }
        public System.DateTime FechaOperacion { get; set; }
    }
}
