//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaPrincipal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaPrincipal()
        {
            this.RegistroDiarioCaja = new HashSet<RegistroDiarioCaja>();
            this.SubMayor = new HashSet<SubMayor>();
            this.CierreCaja = new HashSet<CierreCaja>();
        }
    
        public int CajaID { get; set; }
        public string Nombre { get; set; }
        public string Moneda { get; set; }
        public decimal SaldoActual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroDiarioCaja> RegistroDiarioCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubMayor> SubMayor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CierreCaja> CierreCaja { get; set; }
    }
}
