//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreSubMayor
    {
        public int ID { get; set; }
        public int CierreID { get; set; }
        public int SubMayorID { get; set; }
        public decimal SaldoFinal { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual CierreCaja CierreCaja { get; set; }
        public virtual SubMayor SubMayor { get; set; }
    }
}
