//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_cuenta
    {
        public int id { get; set; }
        public Nullable<int> clienteid { get; set; }
        public Nullable<int> cuentaid { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual cuenta cuenta { get; set; }
    }
}
