//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.cliente_cuenta = new HashSet<cliente_cuenta>();
            this.negocio = new HashSet<negocio>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string nacionalidad { get; set; }
        public string direccion { get; set; }
        public string provincia { get; set; }
        public string municipio { get; set; }
        public string localidad { get; set; }
        public string nit { get; set; }
        public string reeup { get; set; }
        public string renae { get; set; }
        public int tipoClienteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_cuenta> cliente_cuenta { get; set; }
        public virtual tipo_cliente tipo_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<negocio> negocio { get; set; }
    }
}
