//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuenta()
        {
            this.cliente_cuenta = new HashSet<cliente_cuenta>();
        }
    
        public int id { get; set; }
        public string no { get; set; }
        public string tipo_cuenta { get; set; }
        public string agencia { get; set; }
        public string banco { get; set; }
        public string titular { get; set; }
        public string direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_cuenta> cliente_cuenta { get; set; }
    }
}
