//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo
    {
        public int id { get; set; }
        public Nullable<int> areaid { get; set; }
        public Nullable<int> tipo_flujoid { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<float> cantidad { get; set; }
        public Nullable<float> importe { get; set; }
        public string concepto { get; set; }
        public Nullable<float> precio { get; set; }
    
        public virtual area area { get; set; }
        public virtual tipo_flujo tipo_flujo { get; set; }
    }
}
