//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VERCOMEntities : DbContext
    {
        public VERCOMEntities()
            : base("name=VERCOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cliente_cuenta> cliente_cuenta { get; set; }
        public virtual DbSet<cuenta> cuenta { get; set; }
        public virtual DbSet<flujo> flujo { get; set; }
        public virtual DbSet<forma_operacion> forma_operacion { get; set; }
        public virtual DbSet<medio_pago> medio_pago { get; set; }
        public virtual DbSet<negocio> negocio { get; set; }
        public virtual DbSet<operacion> operacion { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<presupuesto> presupuesto { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_servicio> producto_servicio { get; set; }
        public virtual DbSet<punto_venta> punto_venta { get; set; }
        public virtual DbSet<RolePermissions> RolePermissions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<tipo_cliente> tipo_cliente { get; set; }
        public virtual DbSet<tipo_factura> tipo_factura { get; set; }
        public virtual DbSet<tipo_flujo> tipo_flujo { get; set; }
        public virtual DbSet<tipo_operacion> tipo_operacion { get; set; }
        public virtual DbSet<tipo_pago> tipo_pago { get; set; }
        public virtual DbSet<trazas> trazas { get; set; }
        public virtual DbSet<unidad> unidad { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
    }
}
