//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCaja
    {
        public int MovimientoID { get; set; }
        public int SubMayorID { get; set; }
        public string TipoMovimiento { get; set; }
        public decimal Monto { get; set; }
        public string Concepto { get; set; }
        public string ReferenciaExterna { get; set; }
        public string MetodoPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Usuario { get; set; }
    
        public virtual SubMayor SubMayor { get; set; }
    }
}
