//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class negocio
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> productoID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public Nullable<float> cantidad { get; set; }
        public Nullable<int> operacionID { get; set; }
        public Nullable<int> facturaID { get; set; }
        public Nullable<int> medioPagoID { get; set; }
        public string factura { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual forma_operacion forma_operacion { get; set; }
        public virtual medio_pago medio_pago { get; set; }
        public virtual tipo_factura tipo_factura { get; set; }
        public virtual producto_servicio producto_servicio { get; set; }
    }
}
