//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operacion
    {
        public int id { get; set; }
        public Nullable<int> punto_ventaid { get; set; }
        public Nullable<int> productoid { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<float> cantidad { get; set; }
        public Nullable<float> importe { get; set; }
        public Nullable<int> tipo_pagoid { get; set; }
        public Nullable<int> tipo_operacionid { get; set; }
    
        public virtual punto_venta punto_venta { get; set; }
        public virtual tipo_pago tipo_pago { get; set; }
        public virtual tipo_operacion tipo_operacion { get; set; }
        public virtual producto producto { get; set; }
    }
}
