//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto_servicio()
        {
            this.negocio = new HashSet<negocio>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<float> precio { get; set; }
        public Nullable<float> costo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<negocio> negocio { get; set; }
    }
}
