//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.operacion = new HashSet<operacion>();
        }
    
        public int id { get; set; }
        public string cod { get; set; }
        public string nombre { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> costo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> categoriaid { get; set; }
        public Nullable<int> unidadid { get; set; }
        public Nullable<int> areaid { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual area area { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual unidad unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operacion> operacion { get; set; }
    }
}
