//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroDiarioCaja
    {
        public int RegistroID { get; set; }
        public int CajaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal TotalIngresos { get; set; }
        public decimal TotalEgresos { get; set; }
        public decimal SaldoFinal { get; set; }
        public string UsuarioCierre { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CajaPrincipal CajaPrincipal { get; set; }
    }
}
