//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vercom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMayor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMayor()
        {
            this.CierreSubMayor = new HashSet<CierreSubMayor>();
            this.MovimientoCaja = new HashSet<MovimientoCaja>();
        }
    
        public int SubMayorID { get; set; }
        public int CajaID { get; set; }
        public string Nombre { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual CajaPrincipal CajaPrincipal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CierreSubMayor> CierreSubMayor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCaja> MovimientoCaja { get; set; }
    }
}
